[package]
name = "abc39aa2"
version = "0.1.0"
description = "My ICP Ninja-compatible project"
repository = "https://github.com/developer20010605/abc39aa2"

[dependencies]
base = "0.11.1"
# add other motoko deps here if you need them

# VERY IMPORTANT for ICP Ninja:
# Do NOT include a [toolchain] section here.
# Ninja controls which moc/dfx it uses.
